package gui;

import model.Customer;
import service.ManagementService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.UUID;

/**
 * Panel dedicated to the management of Customer entities (CRUD UI).
 * Handles the unique LocalDate field for Last Purchase Date.
 */
public class CustomerPanel extends JPanel {

    private final ManagementService managementService;

    // --- GUI Components (Form) ---
    private JTextField idField, nameField, ageField, membershipLevelField, lastPurchaseDateField;
    private JButton saveButton, deleteButton;
    private JTable customerTable;
    private DefaultTableModel tableModel;

    public CustomerPanel(ManagementService service) {
        this.managementService = service;
        setLayout(new BorderLayout(10, 10)); // Outer layout

        initComponents();
        loadCustomerData(); // Load data when the panel initializes
    }

    private void initComponents() {
        // --- 1. Top Panel (Form and Controls) ---
        JPanel formPanel = createFormPanel();
        add(formPanel, BorderLayout.NORTH);

        // --- 2. Center Panel (Table View) ---
        JScrollPane tableScrollPane = createTablePanel();
        add(tableScrollPane, BorderLayout.CENTER);

        // --- 3. Button Actions ---
        setupActions();
    }

    // =========================================================
    // UI Creation Methods
    // =========================================================

    private JPanel createFormPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createTitledBorder("Customer Details"));

        // A. Input Fields Panel (GridLayout for labels and fields)
        JPanel fieldsPanel = new JPanel(new GridLayout(6, 2, 5, 5));

        // ID Field (Read-only, generated by the system)
        idField = new JTextField();
        idField.setEditable(false);
        idField.setBackground(Color.LIGHT_GRAY);
        fieldsPanel.add(new JLabel("ID (Auto):"));
        fieldsPanel.add(idField);

        nameField = new JTextField();
        fieldsPanel.add(new JLabel("Name:"));
        fieldsPanel.add(nameField);

        ageField = new JTextField();
        fieldsPanel.add(new JLabel("Age:"));
        fieldsPanel.add(ageField);

        membershipLevelField = new JTextField();
        fieldsPanel.add(new JLabel("Membership Level:"));
        fieldsPanel.add(membershipLevelField);

        // Date Field: Crucial reminder for format
        lastPurchaseDateField = new JTextField();
        fieldsPanel.add(new JLabel("Last Purchase Date (YYYY-MM-DD):"));
        fieldsPanel.add(lastPurchaseDateField);

        panel.add(fieldsPanel, BorderLayout.CENTER);

        // B. Control Buttons Panel
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        saveButton = new JButton("Save Customer (Create/Update)");
        deleteButton = new JButton("Delete Selected Customer");
        JButton newButton = new JButton("New/Clear Form");

        buttonPanel.add(newButton);
        buttonPanel.add(saveButton);
        buttonPanel.add(deleteButton);

        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Setup initial state
        newButton.addActionListener(e -> clearForm());
        deleteButton.setEnabled(false);

        return panel;
    }

    private JScrollPane createTablePanel() {
        // Define column headers
        String[] columnNames = {"ID", "Name", "Age", "Membership", "Last Purchase Date"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        customerTable = new JTable(tableModel);

        // Listener to populate the form when a row is clicked
        customerTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && customerTable.getSelectedRow() != -1) {
                populateFormFromTable(customerTable.getSelectedRow());
                deleteButton.setEnabled(true);
            }
        });

        return new JScrollPane(customerTable);
    }

    // =========================================================
    // Data Loading and Mapping Methods
    // =========================================================

    private void loadCustomerData() {
        tableModel.setRowCount(0);

        List<Customer> customers = managementService.getAllCustomers();

        for (Customer cust : customers) {
            Object[] row = new Object[]{
                    cust.getId(),
                    cust.getName(),
                    cust.getAge(),
                    cust.getMembershipLevel(),
                    cust.getLastPurchaseDate().toString() // LocalDate stored as string
            };
            tableModel.addRow(row);
        }
    }

    private void populateFormFromTable(int rowIndex) {
        idField.setText(tableModel.getValueAt(rowIndex, 0).toString());
        nameField.setText(tableModel.getValueAt(rowIndex, 1).toString());
        ageField.setText(tableModel.getValueAt(rowIndex, 2).toString());
        membershipLevelField.setText(tableModel.getValueAt(rowIndex, 3).toString());
        lastPurchaseDateField.setText(tableModel.getValueAt(rowIndex, 4).toString());
    }

    private void clearForm() {
        idField.setText("");
        nameField.setText("");
        ageField.setText("");
        membershipLevelField.setText("");
        lastPurchaseDateField.setText("");
        deleteButton.setEnabled(false);
        customerTable.clearSelection();
    }

    // =========================================================
    // Action Handlers (CRUD Logic)
    // =========================================================

    private void setupActions() {
        saveButton.addActionListener(this::handleSaveAction);
        deleteButton.addActionListener(this::handleDeleteAction);
    }

    private void handleSaveAction(ActionEvent e) {
        String id = idField.getText().isEmpty() ? UUID.randomUUID().toString() : idField.getText();
        String name = nameField.getText();

        try {
            int age = Integer.parseInt(ageField.getText());
            String membershipLevel = membershipLevelField.getText();

            // --- CRITICAL: DATE PARSING ---
            LocalDate lastPurchaseDate = LocalDate.parse(lastPurchaseDateField.getText());

            Customer customer = new Customer(id, name, age, membershipLevel, lastPurchaseDate);

            if (idField.getText().isEmpty()) {
                managementService.saveCustomer(customer); // CREATE
                JOptionPane.showMessageDialog(this, "Customer created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                managementService.updateCustomer(customer); // UPDATE
                JOptionPane.showMessageDialog(this, "Customer updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            clearForm();
            loadCustomerData(); // Refresh the table

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format for Age.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException ex) {
            // New error handler for date input
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // Catches validation error from ManagementService
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void handleDeleteAction(ActionEvent e) {
        String idToDelete = idField.getText();
        if (idToDelete.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete customer ID: " + idToDelete + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = managementService.deleteCustomer(idToDelete);
            if (success) {
                JOptionPane.showMessageDialog(this, "Customer deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadCustomerData(); // Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete customer.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}