package gui;

import model.Employee;
import service.ManagementService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.UUID;
import java.io.IOException;
import java.io.File;
import java.text.NumberFormat;
import java.util.Locale;

/**
 * Panel dedicated to the management of Employee entities (CRUD UI).
 * It interacts exclusively with the ManagementService.
 */
public class EmployeePanel extends JPanel {

    // Custom format for South African Rand (R)
    private static final NumberFormat RAND_FORMATTER = NumberFormat.getCurrencyInstance(new Locale("en", "ZA")); //
     private final ManagementService managementService;
    private final MainFrame mainFrame; // <--- CRITICAL ADDITION: MainFrame reference

    // --- GUI Components (Form) ---
    private JTextField idField, nameField, ageField, salaryField;
    private JComboBox<String> cbJobTitle;
    private JButton saveButton, deleteButton;
    private JButton exportButton;
    private JTable employeeTable;
    private DefaultTableModel tableModel;

    // --- Dropdown Data (New) ---
    private static final String[] JOB_TITLES = {
            "Analyst", "Senior Analyst", "Manager", "Director", "Executive", "Intern", "Other"
    };

    // MODIFIED CONSTRUCTOR: Now accepts MainFrame
    public EmployeePanel(ManagementService service, MainFrame mainFrame) {
        this.managementService = service;
        this.mainFrame = mainFrame; // <--- ASSIGNED HERE
        setLayout(new BorderLayout(10, 10));

        initComponents();
        loadEmployeeData();

        //applyRoleBasedAccessControl();

    }

    private void initComponents() {
        // --- 1. Top Panel (Form and Controls) ---
        JPanel formPanel = createFormPanel();
        add(formPanel, BorderLayout.NORTH);

        // --- 2. Center Panel (Table View) ---
        JScrollPane tableScrollPane = createTablePanel();
        add(tableScrollPane, BorderLayout.CENTER);

        // --- 3. Button Actions ---
        setupActions();
    }

    // =========================================================
    // UI Creation Methods (Unchanged)
    // =========================================================

    private JPanel createFormPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createTitledBorder("Employee Details"));

        // A. Input Fields Panel (GridLayout for labels and fields)
        JPanel fieldsPanel = new JPanel(new GridLayout(6, 2, 5, 5));

        // ID Field (Read-only, generated by the system)
        idField = new JTextField();
        idField.setEditable(false);
        idField.setBackground(Color.LIGHT_GRAY);
        fieldsPanel.add(new JLabel("ID (Auto):"));
        fieldsPanel.add(idField);

        nameField = new JTextField();
        fieldsPanel.add(new JLabel("Name:"));
        fieldsPanel.add(nameField);

        ageField = new JTextField();
        fieldsPanel.add(new JLabel("Age:"));
        fieldsPanel.add(ageField);

        salaryField = new JTextField();
        fieldsPanel.add(new JLabel("Salary:"));
        fieldsPanel.add(salaryField);

        cbJobTitle = new JComboBox<>(JOB_TITLES);
        fieldsPanel.add(new JLabel("Job Title:"));
        fieldsPanel.add(cbJobTitle);

        panel.add(fieldsPanel, BorderLayout.CENTER);

        // B. Control Buttons Panel
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        saveButton = new JButton("Save Employee (Create/Update)");
        deleteButton = new JButton("Delete Selected Employee");
        JButton newButton = new JButton("New/Clear Form");

        // Initialize the Export button for CSV
        exportButton = new JButton("Export to CSV");

        buttonPanel.add(newButton);
        buttonPanel.add(exportButton);
        buttonPanel.add(saveButton);
        buttonPanel.add(deleteButton);

        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Setup initial state
        newButton.addActionListener(e -> clearForm());
        deleteButton.setEnabled(false); // Disable delete until a row is selected

        // Action Listener for Export
        exportButton.addActionListener(this::handleExportAction);

        return panel;
    }

    private JScrollPane createTablePanel() {
        // Define column headers
        String[] columnNames = {"ID", "Name", "Age", "Salary", "Job Title"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            // Override to make the ID column non-editable in the table
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        employeeTable = new JTable(tableModel);

        // Listener to populate the form when a row is clicked (for Read/Update/Delete)
        employeeTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && employeeTable.getSelectedRow() != -1) {
                populateFormFromTable(employeeTable.getSelectedRow());

                // Only enable the delete button if the user has CRUD access
                String role = managementService.getAuthService().getActiveUser().getRole();
                boolean hasCrudAccess = role.equals("Admin") || role.equals("Manager") || role.equals("HR Specialist");

                deleteButton.setEnabled(hasCrudAccess); // <-- RBAC CHECK APPLIED HERE
            }
        });

        return new JScrollPane(employeeTable);
    }

    // =========================================================
    // Data Loading and Mapping Methods (Unchanged)
    // =========================================================

    public void loadEmployeeData() {
        // Clear existing data
        tableModel.setRowCount(0);

        try { // <-- START Robustness: Try-catch for DAO call
            // Get data from the Service layer (READ operation)
            List<Employee> employees = managementService.getAllEmployees();

            for (Employee emp : employees) {
                Object[] row = new Object[]{
                        emp.getId(),
                        emp.getName(),
                        emp.getAge(),
                        RAND_FORMATTER.format(emp.getSalary()), // Format salary for display
                        emp.getJobTitle()
                };
                tableModel.addRow(row);
            }
            mainFrame.updateStatusBar("Employee table loaded successfully.", true); // <-- Status Bar Update (Success)

        } catch (Exception ex) { // Catches DataAccessException or other exceptions
            mainFrame.updateStatusBar("Error loading employee data: " + ex.getMessage(), false); // <-- Status Bar Update (Error)
        }
    }

    private void populateFormFromTable(int rowIndex) {
        idField.setText(tableModel.getValueAt(rowIndex, 0).toString());
        nameField.setText(tableModel.getValueAt(rowIndex, 1).toString());
        ageField.setText(tableModel.getValueAt(rowIndex, 2).toString());

         String rawSalary = tableModel.getValueAt(rowIndex, 3).toString()
                .replaceAll("[^\\d\\.,]", "") // Remove non-digit, non-decimal, non-comma characters
                .replace(",", ""); // Remove thousands comma (assuming dot is decimal)

        salaryField.setText(rawSalary);
        cbJobTitle.setSelectedItem(tableModel.getValueAt(rowIndex, 4).toString());
       }

    private void clearForm() {
        idField.setText("");
        nameField.setText("");
        ageField.setText("");
        salaryField.setText("");
        cbJobTitle.setSelectedIndex(0);
        deleteButton.setEnabled(false);
        employeeTable.clearSelection();
        mainFrame.resetStatusBar();
    }

    // =========================================================
    // Action Handlers (CRUD Logic)
    // =========================================================

    private void setupActions() {
        // --- Save Button Action Listener (Create or Update) ---
        saveButton.addActionListener(this::handleSaveAction);

        // --- Delete Button Action Listener ---
        deleteButton.addActionListener(this::handleDeleteAction);
    }

    private void handleSaveAction(ActionEvent e) {
        // NOTE: Keeping your original UUID generation, although typically database handles IDs.
        String id = idField.getText().isEmpty() ? UUID.randomUUID().toString() : idField.getText();
        String name = nameField.getText();

        try {
            int age = Integer.parseInt(ageField.getText());
            double salary = Double.parseDouble(salaryField.getText());
            String jobTitle = (String) cbJobTitle.getSelectedItem();

            Employee employee = new Employee(id, name, age, salary, jobTitle);

            // Check if it's a new entry or an update
            if (idField.getText().isEmpty()) {
                managementService.saveEmployee(employee); // CREATE
                JOptionPane.showMessageDialog(this, "Employee created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                managementService.updateEmployee(employee); // UPDATE
                JOptionPane.showMessageDialog(this, "Employee updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            clearForm();
            loadEmployeeData(); // Refresh the table

            // CRITICAL FIX: Refresh the Dashboard after successful save/update
            mainFrame.refreshMetricsDashboard();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format for Age or Salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // This catches the validation error thrown by ManagementService
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void handleDeleteAction(ActionEvent e) {
        String idToDelete = idField.getText();
        if (idToDelete.isEmpty()) {
            mainFrame.updateStatusBar("Please select an employee from the table to delete.", false); // <-- Status Bar Error
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete employee ID: " + idToDelete + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try { // Robustness: Try-catch for Delete operation
                boolean success = managementService.deleteEmployee(idToDelete);
                if (success) {
                    mainFrame.updateStatusBar("Employee deleted successfully. ID: " + idToDelete, true); // <-- Status Bar Success
                    clearForm();
                    loadEmployeeData(); // Refresh the table

                    mainFrame.refreshMetricsDashboard();
                } else {
                    mainFrame.updateStatusBar("Error: Failed to delete employee. ID not found or data access issue.", false); // <-- Status Bar Error
                }
            } catch (Exception ex) {
                mainFrame.updateStatusBar("System Error during deletion: " + ex.getMessage(), false); // <-- Status Bar Error
            }
        }
    }

    // =========================================================
    // Export Action Handler (Unchanged)
    // =========================================================

    private void handleExportAction(ActionEvent e) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export Employee Data to CSV");

        // Set default filename and filter
        fileChooser.setSelectedFile(new File("employees_export.csv"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files (*.csv)", "csv");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Ensure .csv extension
            if (!filePath.toLowerCase().endsWith(".csv")) {
                filePath += ".csv";
            }

            try {
                // Call the new CSV method
                managementService.exportEmployeesToCsv(filePath);
                mainFrame.updateStatusBar("Employee data successfully exported to: " + filePath, true);
                JOptionPane.showMessageDialog(this,
                        "Employee data successfully exported to:\n" + filePath,
                        "Export Successful", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error writing file: " + ex.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
                System.err.println("Export failed: " + ex.getMessage());
            }
        }
    }
    // =========================================================
// RBAC Implementation (Fine-Grained Button Control)
// =========================================================

    /**
     * Applies fine-grained control to the CRUD buttons based on the active user's role.
     * Roles with CRUD access: Admin, Manager, HR Specialist
     * Roles with Read-Only access: Data Analyst, Cust. Service Agent (though they shouldn't see this panel)
     */
    public void refreshAccessControls() {
        // Check if a user is logged in before attempting to get the role
        if (managementService.getAuthService().getActiveUser() == null) {
            setCrudEnabled(false);
            exportButton.setEnabled(false);
            return;
        }

        // Retrieve the active user's role from the Authentication Service
        String role = managementService.getAuthService().getActiveUser().getRole();

        // Define which roles have CRUD privileges on EMPLOYEE data
        boolean hasCrudAccess = role.equals("Admin") ||
                role.equals("Manager") ||
                role.equals("HR Specialist");

        // Roles that only have Read access on this panel (but should see it)
        boolean isReadOnly = role.equals("Data Analyst");

        // Set state for the CRUD buttons and input fields
        if (hasCrudAccess) {
            // Full control
            setCrudEnabled(true);
            mainFrame.updateStatusBar("Employee Panel: CRUD mode enabled for " + role, true);
        } else if (isReadOnly) {
            // Read-Only mode
            setCrudEnabled(false);
            mainFrame.updateStatusBar("Employee Panel: Read-Only mode enabled for Data Analyst.", true);
        } else {
            // Any other role (e.g., Customer Service Agent) should ideally be blocked at the tab level,
            // but if they somehow bypass the MainFrame, we set them to Read-Only as a fallback.
            setCrudEnabled(false);
            // NOTE: The tab logic in MainFrame should prevent Cust. Service Agent from seeing this tab.
        }

        // Data Analyst role is allowed to Export for reporting purposes
        exportButton.setEnabled(role.equals("Admin") || role.equals("Manager") || role.equals("HR Specialist") || role.equals("Data Analyst"));
    }

    /**
     * Helper method to enable or disable CRUD buttons and input fields.
     */
    private void setCrudEnabled(boolean enabled) {
        saveButton.setEnabled(enabled);
        deleteButton.setEnabled(false); // Always disable delete initially until selection is made

        // Disable editing in the form fields
        nameField.setEditable(enabled);
        ageField.setEditable(enabled);
        salaryField.setEditable(enabled);
        cbJobTitle.setEnabled(enabled);

        // Make the table non-editable for Read-Only roles
        // We do this by toggling the DefaultTableModel's behavior or, more simply, the whole panel's appearance.
        employeeTable.setEnabled(enabled);
    }
}