package gui;

import model.Employee;
import service.ManagementService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.UUID;
import java.io.IOException;

/**
 * Panel dedicated to the management of Employee entities (CRUD UI).
 * It interacts exclusively with the ManagementService.
 */
public class EmployeePanel extends JPanel {

    private final ManagementService managementService;

    // --- GUI Components (Form) ---
    private JTextField idField, nameField, ageField, salaryField, jobTitleField;
    private JButton saveButton, deleteButton;
    private JTable employeeTable;
    private DefaultTableModel tableModel;

    public EmployeePanel(ManagementService service) {
        this.managementService = service;
        setLayout(new BorderLayout(10, 10)); // Outer layout

        initComponents();
        loadEmployeeData(); // Load data when the panel initializes
    }

    private void initComponents() {
        // --- 1. Top Panel (Form and Controls) ---
        JPanel formPanel = createFormPanel();
        add(formPanel, BorderLayout.NORTH);

        // --- 2. Center Panel (Table View) ---
        JScrollPane tableScrollPane = createTablePanel();
        add(tableScrollPane, BorderLayout.CENTER);

        // --- 3. Button Actions ---
        setupActions();
    }

    // =========================================================
    // UI Creation Methods
    // =========================================================

    private JPanel createFormPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createTitledBorder("Employee Details"));

        // A. Input Fields Panel (GridLayout for labels and fields)
        JPanel fieldsPanel = new JPanel(new GridLayout(6, 2, 5, 5));

        // ID Field (Read-only, generated by the system)
        idField = new JTextField();
        idField.setEditable(false);
        idField.setBackground(Color.LIGHT_GRAY);
        fieldsPanel.add(new JLabel("ID (Auto):"));
        fieldsPanel.add(idField);

        nameField = new JTextField();
        fieldsPanel.add(new JLabel("Name:"));
        fieldsPanel.add(nameField);

        ageField = new JTextField();
        fieldsPanel.add(new JLabel("Age:"));
        fieldsPanel.add(ageField);

        salaryField = new JTextField();
        fieldsPanel.add(new JLabel("Salary:"));
        fieldsPanel.add(salaryField);

        jobTitleField = new JTextField();
        fieldsPanel.add(new JLabel("Job Title:"));
        fieldsPanel.add(jobTitleField);

        panel.add(fieldsPanel, BorderLayout.CENTER);

        // B. Control Buttons Panel
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        saveButton = new JButton("Save Employee (Create/Update)");
        deleteButton = new JButton("Delete Selected Employee");
        JButton newButton = new JButton("New/Clear Form");

        JButton exportButton = new JButton("Export Employees to JSON");

        buttonPanel.add(newButton);
        buttonPanel.add(exportButton);
        buttonPanel.add(saveButton);
        buttonPanel.add(deleteButton);

        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Setup initial state
        newButton.addActionListener(e -> clearForm());
        deleteButton.setEnabled(false); // Disable delete until a row is selected

        // --- NEW: Add Action Listener for Export ---
        exportButton.addActionListener(this::handleExportAction);

        return panel;
    }

    private JScrollPane createTablePanel() {
        // Define column headers
        String[] columnNames = {"ID", "Name", "Age", "Salary", "Job Title"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            // Override to make the ID column non-editable in the table
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        employeeTable = new JTable(tableModel);

        // Listener to populate the form when a row is clicked (for Read/Update/Delete)
        employeeTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && employeeTable.getSelectedRow() != -1) {
                populateFormFromTable(employeeTable.getSelectedRow());
                deleteButton.setEnabled(true);
            }
        });

        return new JScrollPane(employeeTable);
    }

    // =========================================================
    // Data Loading and Mapping Methods
    // =========================================================

    private void loadEmployeeData() {
        // Clear existing data
        tableModel.setRowCount(0);

        // Get data from the Service layer (READ operation)
        List<Employee> employees = managementService.getAllEmployees();

        for (Employee emp : employees) {
            Object[] row = new Object[]{
                    emp.getId(),
                    emp.getName(),
                    emp.getAge(),
                    String.format("%.2f", emp.getSalary()), // Format salary for display
                    emp.getJobTitle()
            };
            tableModel.addRow(row);
        }
    }

    private void populateFormFromTable(int rowIndex) {
        idField.setText(tableModel.getValueAt(rowIndex, 0).toString());
        nameField.setText(tableModel.getValueAt(rowIndex, 1).toString());
        ageField.setText(tableModel.getValueAt(rowIndex, 2).toString());
        // Salary will have a comma/format applied, so we might need to clean it up for editing,
        // but for now, we'll use the raw value if possible.
        salaryField.setText(tableModel.getValueAt(rowIndex, 3).toString().replace(",", ""));
        jobTitleField.setText(tableModel.getValueAt(rowIndex, 4).toString());
    }

    private void clearForm() {
        idField.setText("");
        nameField.setText("");
        ageField.setText("");
        salaryField.setText("");
        jobTitleField.setText("");
        deleteButton.setEnabled(false);
        employeeTable.clearSelection();
    }

    // =========================================================
    // Action Handlers (CRUD Logic)
    // =========================================================

    private void setupActions() {
        // --- Save Button Action Listener (Create or Update) ---
        saveButton.addActionListener(this::handleSaveAction);

        // --- Delete Button Action Listener ---
        deleteButton.addActionListener(this::handleDeleteAction);
    }

    private void handleSaveAction(ActionEvent e) {
        String id = idField.getText().isEmpty() ? UUID.randomUUID().toString() : idField.getText();
        String name = nameField.getText();

        try {
            int age = Integer.parseInt(ageField.getText());
            double salary = Double.parseDouble(salaryField.getText());
            String jobTitle = jobTitleField.getText();

            Employee employee = new Employee(id, name, age, salary, jobTitle);

            // Check if it's a new entry or an update
            if (idField.getText().isEmpty()) {
                managementService.saveEmployee(employee); // CREATE
                JOptionPane.showMessageDialog(this, "Employee created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                managementService.updateEmployee(employee); // UPDATE
                JOptionPane.showMessageDialog(this, "Employee updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            clearForm();
            loadEmployeeData(); // Refresh the table

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format for Age or Salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // This catches the validation error thrown by ManagementService
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void handleDeleteAction(ActionEvent e) {
        String idToDelete = idField.getText();
        if (idToDelete.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete employee ID: " + idToDelete + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = managementService.deleteEmployee(idToDelete);
            if (success) {
                JOptionPane.showMessageDialog(this, "Employee deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadEmployeeData(); // Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete employee.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // =========================================================
    // Export Action Handler
    // =========================================================

    private void handleExportAction(ActionEvent e) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify file to save JSON export");

        // Suggest a default filename
        fileChooser.setSelectedFile(new java.io.File("employees_export.json"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();

            try {
                // Call the Service Layer method to handle the export logic
                managementService.exportEmployeesToJson(fileToSave.getAbsolutePath());

                JOptionPane.showMessageDialog(this,
                        "Employee data successfully exported to:\n" + fileToSave.getAbsolutePath(),
                        "Export Successful", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error writing file: " + ex.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
                System.err.println("Export failed: " + ex.getMessage());
            }
        }
    }
}